# Generated by Django 4.2.1 on 2023-05-28 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0004_logindetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetails',
            name='login_date',
        ),
        migrations.AddField(
            model_name='logindetails',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logindetails',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
