# Generated by Django 4.2.1 on 2023-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Customer care', 'Customer care'), ('Booking Support (Residential Property)', 'Booking Support (Residential Property)'), ('Booking Support (Commercial Property)', 'Booking Support (Commercial Property)'), ('Booking Support (Farmland Property)', 'Booking Support (Farmland Property)')], default='Customer care', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM')], default='6 PM', max_length=10),
        ),
    ]
